import {label,sortRows,toCSV,workbookBuffer} from './reports.js';
import {mountBillingEditor} from './billing.js';
const PERSONAL=['category','title_rank','first_name','surname','post_nominals','email','mobile','service','discipline','position_role','dietary_requirements','date_of_birth','equipment_hire_required','boot_size'];
const REQUEST=['other_information','accommodation_required','accommodation_from','accommodation_to','hotel_preference','room_share_requested','room_share_with','room_sharing_option','dinners_with_guests','arrival_method','arrival_airport_station','arrival_flight_number','arrival_datetime','arrival_resort_datetime','arrival_transfer_requested','arrival_special_transfer_datetime','departure_method','departure_airport_station','departure_flight_number','departure_datetime','departure_resort_datetime','departure_transfer_requested','departure_special_transfer_datetime','lift_pass_required','first_ski_day','last_ski_day','carre_neige_requested','lessons_required','lesson_type','lesson_dates','arrival_details','departure_details','in_resort_details'];
const SOURCE_IDENTITY=new Set([...PERSONAL,'id','event_id','attendee_id','user_id','invitation_id','known_as','display_company','privacy_acknowledged_at','public_reference']);
const OPERATIONAL={hotels:['actual_check_in','actual_check_out','billing_from','billing_to','rate_code','protocol_confirmed'],lift_passes:['required','start_date','end_date','carre_neige_required','chargeable','rate_code','protocol_confirmed','notes'],transport:['method_of_transport','airport_station','flight_travel_number','travel_datetime','resort_datetime','transfer_requested','transfer_service','transfer_chargeable','special_transfer_datetime','assignment_notes','protocol_confirmed'],services:['service_date','title','status','quantity','chargeable','rate_code','attendee_details','protocol_notes']};
const DEFAULTS={transfer_review:['first_name','surname','direction','airport_station','transfer_requested','protocol_confirmed','transfer_chargeable','billing_reviewed','billing_review_notes'],...Object.fromEntries(Object.entries(OPERATIONAL).map(([k,v])=>[k,['first_name','surname',...v]])),registrations:['first_name','surname','display_company','email','mobile','category','registration_status','dietary_requirements','equipment_hire_required','boot_size'],charges:['first_name','surname','company','description','source_type','quantity','billing_from','billing_to','start_date','end_date','rate_code','unit_price','net_amount','vat_amount','gross_amount','locked','notes'],billing:['first_name','surname','company','email','estimated_gross_total','ready_for_invoice','data_checked','package_complete','chargeable_transfer','transfer_package','invoice_stages'],invoices:['invoice_reference','recipient','email','invoice_type','gross_total','status','payment_link','purchase_order_reference','due_date','dispatch_status']};
export function typedValue(text,original,key){
 key=key.replace(/^submitted_/,'');
 if(typeof original==='boolean'||key.endsWith('_required')||key.endsWith('_requested')){if(!['true','false',''].includes(text.toLowerCase()))throw Error('Enter true or false');return text===''?null:text.toLowerCase()==='true';}
 if(typeof original==='number'||key==='quantity'){const n=Number(text);if(!Number.isFinite(n)||text.trim()==='')throw Error('Enter a number');return n;}
 if(Array.isArray(original)||key==='lesson_dates')return text.trim()?JSON.parse(text):[];
 return text===''?null:text;
}
export const displayValue=v=>v==null?'':typeof v==='object'?JSON.stringify(v):String(v);
export function flattenRegistration(row){const out={...row};for(const [k,v] of Object.entries(row.requested||{}))out['submitted_'+k]=v;return out;}
export function registrationEditable(r,c){return PERSONAL.includes(c)||(c.startsWith('submitted_')&&!SOURCE_IDENTITY.has(c.slice(10))&&Object.hasOwn(r.requested||{},c.slice(10))&&!!(r.registration_id||r.registration_intake_id||r.entity==='booking_requests'))||(r.entity==='attendees'?(['known_as','display_company','attendee_notes','protocol_notes'].includes(c)||(r.registration_id&&REQUEST.includes(c))):REQUEST.includes(c));}
export function createWorkspaces({client,eventId,isTest,isReadOnly=()=>false,getProfile,getWorkingEvent,escapeHtml:h,toast,openAttendee}){
 const s={sheet:'registrations',rows:[],columns:[],visible:[],selected:new Set(),edits:new Map(),versions:new Map(),filters:{},sort:'surname',asc:true,busy:false,results:[],jobs:[],companies:[],rates:[]};
 const finance=()=>['admin','finance'].includes(getProfile()?.app_role);
 const editor=()=>!isReadOnly()&&['admin','protocol','operations'].includes(getProfile()?.app_role);
 const rpc=async(name,args)=>{const r=await client.rpc(name,args);if(r.error)throw Error(r.error.message);return r.data;};
 const root=()=>getWorkingEvent&&getWorkingEvent()!==eventId?null:document.querySelector('#bulkWorkspace');
 const eligible=()=>s.rows.filter(r=>Object.entries(s.filters).every(([k,v])=>!v||displayValue(r[k]).toLowerCase().includes(v.toLowerCase())));
 const visibleRows=()=>sortRows(eligible(),s.sort,s.asc);
 function editable(r,c){if(isReadOnly())return false;if(s.sheet==='transfer_review')return finance()&&['transfer_chargeable','billing_reviewed','billing_review_notes'].includes(c);if(OPERATIONAL[s.sheet])return editor()&&OPERATIONAL[s.sheet].includes(c);if(s.sheet==='registrations')return editor()&&registrationEditable(r,c);
 if(!finance())return false;
 if(s.sheet==='invoices')return ['draft','awaiting_billing_update','ready_for_review','approved'].includes(r.status)&&!['queued','processing','accepted','unknown','captured'].includes(r.dispatch_status)&&['payment_link','purchase_order_reference','due_date','notes'].includes(c);
 return s.sheet==='charges'&&!r.locked&&((r.entity==='usage'&&['quantity','rate_code','notes'].includes(c))||(r.entity==='stay'&&r.protocol_confirmed&&['billing_from','billing_to','rate_code'].includes(c))||(r.entity==='lift_pass'&&r.protocol_confirmed&&['start_date','end_date','rate_code','chargeable'].includes(c)));
 }
 function markup(){return '<section class="surface"><div class="surface-body" id="bulkWorkspace" aria-live="polite">Loading worksheets…</div></section>';}
 async function load(){if(!finance())s.sheet='registrations';await refresh();}
 async function refresh(){s.busy=true;render();try{
 const [rows,jobs]=await Promise.all([rpc('get_bulk_workspace',{p_event_id:eventId,p_sheet:s.sheet}),finance()?client.from('invoice_dispatch_jobs').select('id,invoice_id,status,error_message,capture_only').eq('event_id',eventId):Promise.resolve({data:[]})]);
 if(jobs.error)throw Error(jobs.error.message);s.jobs=jobs.data||[];
 s.rows=rows.map(r=>s.sheet==='registrations'?flattenRegistration(r):s.sheet==='invoices'?{...r,dispatch_status:s.jobs.find(j=>j.invoice_id===r.id)?.status||r.delivery?.[0]?.delivery_status||'not queued'}:r);
 s.columns=[...new Set(s.rows.flatMap(Object.keys))].filter(k=>s.sheet==='registrations'?(PERSONAL.includes(k)||['known_as','display_company','registration_status','attendance_status','attendee_notes','protocol_notes'].includes(k)||k.startsWith('submitted_')):!['version','entity','requested','source_payload'].includes(k));
 if(!s.visible.length)s.visible=DEFAULTS[s.sheet].filter(c=>s.columns.includes(c));
 s.selected=new Set([...s.selected].filter(id=>s.rows.some(r=>r.id===id)));
 if(finance()&&!s.companies.length){const result=await client.from('organisations').select('id,organisation_name,billing_name').eq('active',true).order('organisation_name');if(result.error)throw Error(result.error.message);s.companies=result.data;}
 if(finance()&&!s.rates.length){const result=await client.from('rate_card').select('rate_code,description,charge_category').eq('event_id',eventId).eq('active',true).eq('status','approved');if(result.error)throw Error(result.error.message);s.rates=result.data;}
 }catch(e){s.results=[{error:e.message}];}finally{s.busy=false;render();}}
 function stage(r,c,text){const value=typedValue(text,r[c],c);if(!s.versions.has(r.id))s.versions.set(r.id,r.version);const edit=s.edits.get(r.id)||{};edit[c]=value;s.edits.set(r.id,edit);root().querySelector('#bulkSave').disabled=false;root().querySelector('#bulkDirty').textContent=`${s.edits.size} unsaved rows`;}
 function render(){const el=root();if(!el)return;const rows=visibleRows();
 el.innerHTML=`<div class="report-toolbar"><label>Worksheet<select id="bulkSheet" ${s.busy?'disabled':''}>${[['registrations','1. Registrations'],...Object.keys(OPERATIONAL).map(k=>[k,label(k)]),...(finance()?[['transfer_review','Transfer billing review'],['charges','2. Charges'],['billing','3. Billing readiness'],['invoices','4. Invoices & dispatch']]:[])].map(([v,l])=>`<option value="${v}" ${s.sheet===v?'selected':''}>${l}</option>`).join('')}</select></label><button class="btn btn-ghost" id="bulkRefresh" ${s.busy?'disabled':''}>Refresh</button><button class="btn btn-primary" id="bulkSave" ${isReadOnly()||s.busy||!s.edits.size?'disabled':''}>Save changed rows</button><button class="btn btn-ghost" id="bulkDiscard">Discard unsaved edits</button><span id="bulkDirty">${s.edits.size} unsaved rows</span></div>
 <p class="muted small">${isReadOnly()?'Historic 2026 replay: all records are read-only. Filters, column selection and exports remain available. ':''}${OPERATIONAL[s.sheet]?'Edit operational records in rows. Confirmed lift-pass edits submit justified requests for Admin approval; they do not immediately change the confirmed pass.':s.sheet==='registrations'?'Edit personal details and submitted form answers in the table. Saves update the linked attendee, booking or intake record and are audited. Confirmed hotel, lift and travel records retain their operational approval controls. Choose columns to see every submitted field.':s.sheet==='charges'?'Edit usage quantities and rates, or confirmed accommodation billing dates and rates, directly here. Confirmed lift-pass changes submit a justified request for Admin approval. Invoice totals recalculate from the source; confirmed invoices stay locked.':s.sheet==='billing'?'Review charges, choose a transfer/admin package and allocate the payer. Mark checked after reviewing the source records, then generate the selected invoices. For an airport transfer, confirm the trip in Protocol and mark it chargeable and reviewed in Transfer billing review.':'Enter or paste payment links before dispatch. Select invoices to confirm, review recipients and send individually in one batch. Accepted means accepted by the email provider, not confirmed receipt.'} ${isReadOnly()?'':' Paste a spreadsheet range starting in an editable cell; save all changed rows together.'}</p>
 <div class="report-actions"><strong>${s.busy?'Loading…':`${rows.length} rows · ${s.selected.size} selected`}</strong><button id="bulkCSV" class="btn btn-ghost">CSV</button><button id="bulkXLSX" class="btn btn-ghost">Excel</button>${s.sheet==='billing'&&!isReadOnly()?'<button class="btn btn-ghost" data-action="check">Mark selected checked</button><button class="btn btn-primary" data-action="generate">Generate selected invoices</button>':''}${s.sheet==='invoices'&&!isReadOnly()?`<button class="btn btn-ghost" data-action="confirm">Confirm selected invoices</button><button class="btn btn-primary" id="bulkReview">Review ${isTest?'test dispatch':'& send'}</button><button class="btn btn-ghost" id="bulkResume">Resume queued invoices</button>`:''}</div>
 ${s.sheet==='billing'&&!isReadOnly()?`<details><summary>Apply a payer choice to selected attendees</summary><div class="report-toolbar"><label>Company<select id="bulkCompany"><option value="">Individual pays all</option>${s.companies.map(o=>`<option value="${h(o.id)}">${h(o.billing_name||o.organisation_name)}</option>`).join('')}</select></label><label>Company percentage of each item<input id="bulkPercent" type="number" min="0" max="100" value="100"></label><label>Company format<select id="bulkLayout"><option value="combined">Combined company invoice</option><option value="separate">Separate company invoice per attendee</option></select></label><button id="bulkPayer" class="btn btn-ghost">Save selected payer plans</button></div><p>Use “Item allocations” on a row to assign whole items, amounts or percentages individually.</p></details>`:''}
 <details><summary>Choose columns</summary><div class="report-columns">${s.columns.map(c=>`<label><input type="checkbox" data-col="${h(c)}" ${s.visible.includes(c)?'checked':''}> ${h(label(c))}</label>`).join('')}</div></details>
 <div class="report-grid bulk-grid"><table class="data-table"><thead><tr><th><input type="checkbox" id="bulkAll" aria-label="Select visible rows" ${rows.length&&rows.every(r=>s.selected.has(r.id))?'checked':''}></th>${s.visible.map(c=>`<th><button data-sort="${h(c)}">${h(label(c))}${s.sort===c?(s.asc?' ↑':' ↓'):''}</button><input data-filter="${h(c)}" aria-label="Filter ${h(label(c))}" value="${h(s.filters[c]||'')}"></th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map((r,ri)=>`<tr><td><input type="checkbox" data-select="${h(r.id)}" aria-label="Select ${h(r.surname||r.invoice_reference||r.id)}" ${s.selected.has(r.id)?'checked':''}></td>${s.visible.map((c,ci)=>`<td>${editable(r,c)?`<input data-cell="${ri}:${ci}" aria-label="${h(label(c))} for ${h(r.surname||r.invoice_reference)}" class="${s.edits.get(r.id)?.[c]!==undefined?'dirty':''}" value="${h(displayValue(s.edits.get(r.id)?.[c]!==undefined?s.edits.get(r.id)[c]:r[c]))}">`:`<span>${h(displayValue(r[c]))}</span>`}</td>`).join('')}<td>${s.sheet==='billing'&&!isReadOnly()?`<button data-plan="${h(r.id)}">Item allocations</button><select data-package="${h(r.id)}" aria-label="Transfer package for ${h(r.surname)}"><option value="">Choose package</option>${s.rates.filter(x=>['admin','transfer'].includes(x.charge_category)).map(x=>`<option value="${h(x.rate_code)}" ${r.transfer_package===x.rate_code?'selected':''}>${h(x.description)}</option>`).join('')}</select>`:''}${s.sheet==='registrations'&&r.entity==='attendees'||s.sheet==='charges'?`<button data-open="${h(r.attendee_id||r.id)}">Operational details</button>`:''}${s.sheet==='invoices'&&['approved','issued','paid'].includes(r.status)?`<button data-pdf="${h(r.id)}">PDF</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 <div id="bulkReviewPanel"></div><div id="bulkPlan"></div><div role="status" id="bulkResults">${s.results.map(r=>`<p class="${r.error?'notice error':''}">${h(r.name||r.id||'')}${r.error?': '+h(r.error):r.ok?' — completed':''}</p>`).join('')}</div>`;
 el.querySelector('#bulkSheet').onchange=async e=>{if(s.edits.size){toast('Save changed rows before switching worksheets');e.target.value=s.sheet;return;}s.sheet=e.target.value;s.visible=[];s.selected.clear();s.filters={};s.results=[];await refresh();};
 el.querySelector('#bulkRefresh').onclick=()=>s.edits.size?toast('Save changed rows before refreshing'):refresh();
 el.querySelectorAll('[data-col]').forEach(b=>b.onchange=()=>{s.visible=s.columns.filter(c=>c===b.dataset.col?b.checked:s.visible.includes(c));render();});
 el.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{s.asc=s.sort===b.dataset.sort?!s.asc:true;s.sort=b.dataset.sort;render();});
 el.querySelectorAll('[data-filter]').forEach(b=>b.onchange=()=>{s.filters[b.dataset.filter]=b.value;render();});
 el.querySelector('#bulkAll').onchange=e=>{rows.forEach(r=>e.target.checked?s.selected.add(r.id):s.selected.delete(r.id));render();};
 el.querySelectorAll('[data-select]').forEach(b=>b.onchange=()=>{b.checked?s.selected.add(b.dataset.select):s.selected.delete(b.dataset.select);render();});
 el.querySelectorAll('[data-cell]').forEach(input=>{const [ri,ci]=input.dataset.cell.split(':').map(Number);input.onchange=()=>{try{stage(rows[ri],s.visible[ci],input.value);input.classList.add('dirty');}catch(e){toast(e.message);}};input.onpaste=e=>{const text=e.clipboardData.getData('text/plain');if(!/[\t\n]/.test(text))return;e.preventDefault();try{const staged=[];text.replace(/\r/g,'').replace(/\n$/,'').split('\n').forEach((line,y)=>line.split('\t').forEach((v,x)=>{const r=rows[ri+y],c=s.visible[ci+x];if(!r||!c||!editable(r,c))throw Error('Pasted range includes a read-only cell');typedValue(v,r[c],c);staged.push([r,c,v]);}));staged.forEach(args=>stage(...args));render();}catch(error){toast(error.message);}};});
 el.querySelector('#bulkSave').onclick=save;el.querySelector('#bulkDiscard').onclick=()=>{s.edits.clear();s.versions.clear();refresh();};
 el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>batch(b.dataset.action));
 el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openAttendee(b.dataset.open));
 el.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>mountBillingEditor({el:el.querySelector('#bulkPlan'),supabase:client,attendeeId:b.dataset.plan,eventId,organisations:s.companies,isCurrent:()=>!!root(),onSaved:refresh,onDrafts:refresh}).catch(e=>toast(e.message)));
 el.querySelectorAll('[data-package]').forEach(b=>b.onchange=()=>runRows([b.dataset.package],id=>rpc('save_finance_transfer_package',{p_attendee_id:id,p_rate_code:b.value,p_waived:false,p_notes:'Selected in billing worksheet'})));
 el.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=async()=>{try{const res=await client.functions.invoke('invoice-delivery',{body:{action:'document',invoice_id:b.dataset.pdf}});if(res.error)throw res.error;download(res.data,`invoice-${b.dataset.pdf}.pdf`,'application/pdf');}catch(e){toast(e.message);}});
 el.querySelector('#bulkCSV').onclick=()=>exportRows('csv');el.querySelector('#bulkXLSX').onclick=()=>exportRows('xlsx');
 if(el.querySelector('#bulkPayer'))el.querySelector('#bulkPayer').onclick=()=>{const org=el.querySelector('#bulkCompany').value,percent=Number(el.querySelector('#bulkPercent').value),layout=el.querySelector('#bulkLayout').value;if(!Number.isFinite(percent)||percent<0||percent>100)return toast('Enter a percentage between 0 and 100');runRows([...s.selected],async id=>{const data=await rpc('get_attendee_billing_plan',{p_attendee_id:id});return rpc('save_attendee_billing_plan',{p_attendee_id:id,p_organisation_id:org||null,p_company_layout:layout,p_allocations:Object.fromEntries(data.charges.map(c=>[c.charge_key,{kind:'percent',value:org?percent:0}])),p_signature:data.signature,p_revision:data.plan?.revision||0});});};
 if(el.querySelector('#bulkReview'))el.querySelector('#bulkReview').onclick=review;
 if(el.querySelector('#bulkResume'))el.querySelector('#bulkResume').onclick=()=>dispatch(s.jobs.filter(j=>j.status==='queued'));
 if(s.busy)el.querySelectorAll('button,input,select').forEach(x=>x.disabled=true);
 }
 function downloadableRows(rows){return rows.map(r=>s.sheet==='registrations'?flattenRegistration(r):r);}
 function download(data,name,type){const u=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 async function exportRows(format){if(s.edits.size)return toast('Save changed rows before exporting');s.busy=true;render();try{const rows=visibleRows(),data=await rpc('export_bulk_workspace',{p_event_id:eventId,p_sheet:s.sheet,p_format:format,p_ids:rows.map(r=>r.id),p_columns:s.visible,p_filters:{...s.filters,sort:s.sort,ascending:s.asc}}),byId=new Map(downloadableRows(data.rows).map(r=>[r.id,r])),ordered=rows.map(r=>byId.get(r.id)).filter(Boolean);if(format==='csv')download(toCSV(ordered,s.visible),`ISSSC-${s.sheet}.csv`,'text/csv');else{if(!globalThis.ExcelJS)await import('/vendor/exceljs-4.4.0.min.js');download(await workbookBuffer(globalThis.ExcelJS,[{name:s.sheet,rows:ordered,columns:s.visible}]),`ISSSC-${s.sheet}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}s.results=[{name:`Export audited: ${data.audit_id}`}];}catch(e){s.results=[{error:e.message}];}finally{s.busy=false;render();}}
 async function runRows(ids,fn){if(s.busy)return;if(!ids.length)return toast('Select rows first');if(s.edits.size)return toast('Save changed rows first');s.busy=true;s.results=[];render();try{for(const id of ids){try{await fn(id);s.results.push({id,ok:true});}catch(e){s.results.push({id,error:e.message});}render();}}finally{await refresh();}}
 async function save(){
  if(s.busy)return;
  const needsReason=s.sheet==='charges'||s.sheet==='lift_passes'||(s.sheet==='transfer_review'&&[...s.edits.values()].some(p=>Object.hasOwn(p,'transfer_chargeable')));
  const reason=needsReason?prompt(s.sheet==='lift_passes'?'Justification for the proposed lift-pass changes (confirmed passes require Admin approval)':'Reason for these charge amendments'):null;
  if(needsReason&&!reason?.trim())return;
  s.busy=true;s.results=[];render();
  try{
   for(const [id,patch] of [...s.edits]){
    const row=s.rows.find(r=>r.id===id);
    try{
     await rpc('save_bulk_cell',{p_event_id:eventId,p_sheet:s.sheet,p_id:id,p_version:s.versions.get(id),p_patch:patch,p_reason:reason});
     s.edits.delete(id);s.versions.delete(id);
     s.results.push({id,ok:true,name:(s.sheet==='lift_passes'||s.sheet==='charges'&&row.entity==='lift_pass')&&row.protocol_confirmed?'Lift change requested — awaiting Admin approval':id});
     // Every charge row for one attendee shares a source signature. Re-read it
     // after each save so a pasted set of charges for that attendee can continue.
     if(s.sheet==='charges'&&[...s.edits.keys()].some(key=>s.rows.find(r=>r.id===key)?.attendee_id===row.attendee_id)){
      const current=await rpc('get_bulk_workspace',{p_event_id:eventId,p_sheet:'charges'});
      for(const pendingId of s.edits.keys()){
       const pending=s.rows.find(r=>r.id===pendingId);
       if(pending?.attendee_id!==row.attendee_id)continue;
       const next=current.find(r=>r.id===pendingId);
       if(next)s.versions.set(pendingId,next.version);
      }
     }
    }catch(e){s.results.push({id,error:e.message});}
   }
  }finally{await refresh();}
 }
 async function batch(action){if(s.edits.size)return toast('Save changed rows first');if(!s.selected.size)return toast('Select rows first');if(action==='confirm'&&!confirm(`Confirm ${s.selected.size} selected invoices? Charges become immutable.`))return;s.busy=true;render();try{s.results=await rpc('bulk_billing_action',{p_event_id:eventId,p_action:action,p_ids:[...s.selected]});}catch(e){s.results=[{error:e.message}];}finally{await refresh();}}
 function review(){if(s.edits.size)return toast('Save changed rows first');const rows=s.rows.filter(r=>s.selected.has(r.id));if(!rows.length)return toast('Select invoices first');const el=root().querySelector('#bulkReviewPanel');el.innerHTML=`<div class="notice"><h3>${isTest?'Test capture — no emails will be sent':'Review selected invoice dispatch'}</h3><p>${rows.length} invoices · £${(rows.reduce((sum,r)=>sum+Math.round(Number(r.gross_total)*100),0)/100).toFixed(2)}</p>${rows.map(r=>`<p>${h(r.invoice_reference)} → ${h(r.email||'MISSING EMAIL')} · £${h(r.gross_total)} · ${h(r.payment_link||'Payment instructions only')} · ${h(r.status)}</p>`).join('')}<button id="bulkSend" class="btn btn-primary">${isTest?'Capture test invoices':'Send selected invoices'}</button></div>`;el.querySelector('#bulkSend').onclick=async()=>{s.busy=true;render();try{const results=await rpc('queue_invoice_dispatch',{p_event_id:eventId,p_ids:rows.map(r=>r.id),p_capture:isTest});s.results=results;await dispatch(results.filter(r=>r.ok&&r.job.status==='queued').map(r=>r.job));}catch(e){s.results=[{error:e.message}];}finally{await refresh();}};}
 async function dispatch(jobs){s.busy=true;render();try{for(const job of jobs){const r=await client.functions.invoke('invoice-delivery',{body:{action:'dispatch',job_id:job.id}});s.results.push({id:job.invoice_id,ok:!r.error&&r.data?.ok,error:r.error?.message||r.data?.error});render();}}finally{await refresh();}}
 return {markup,load};
}
