import test from 'node:test';import assert from 'node:assert/strict';import ExcelJS from 'exceljs';import {loadDB} from './load-db.mjs';import {workbookBuffer} from '../reports.js';import {typedValue,flattenRegistration,registrationEditable} from '../workspaces.js';
const admin='e0000000-0000-4000-8000-000000000001',finance='e0000000-0000-4000-8000-000000000002',protocol='e0000000-0000-4000-8000-000000000003',event='e1000000-0000-4000-8000-000000000001';
export async function seedBulk(db){await db.exec(`insert into auth.users(id) values('${admin}'),('${finance}'),('${protocol}');insert into profiles(id,app_role,active) values('${admin}','admin',true),('${finance}','finance',true),('${protocol}','protocol',true);
select set_config('request.jwt.claim.sub','${admin}',false);
insert into events(id,name,event_year,start_date,end_date,invoice_prefix,is_test,delivery_disabled,active,invoice_issuer_name,invoice_issuer_address,invoice_payment_instructions,billing_configuration_confirmed) values('${event}','ISSSC 2028 BULK TRAINING',2028,'2028-01-30','2028-02-06','TEST-BULK',true,true,false,'Training issuer','Training address','Use the individual payment link.',true);
insert into rate_card(event_id,rate_code,description,charge_category,unit,unit_price,vat_rate,status) values('${event}','LESSON','Lesson','lesson','session',100,20,'approved'),('${event}','2028_ADMIN_ONLY','Admin','admin','package',0,0,'approved');
insert into attendees(id,event_id,first_name,surname,email,category) select ('e2000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'${event}','Training '||n,'Person '||n,'training'||n||'@example.invalid','Sponsor' from generate_series(1,20)n;
insert into usage_extras(attendee_id,category,quantity,rate_code,chargeable) select id,'lesson',1,'LESSON',true from attendees where event_id='${event}';`);}
test('20-person bulk workflow and isolation',async t=>{const db=await loadDB();const rpc=async(n,args)=>(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;const actor=async(id,role='authenticated')=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role ${role};`);let ids,invoices;
try{await seedBulk(db);await actor(admin);ids=(await rpc('get_bulk_workspace',[event,'registrations'])).map(r=>r.id);
await t.test('twenty registrations, audited edit and stale overwrite rejected',async()=>{assert.equal(ids.length,20);let r=(await rpc('get_bulk_workspace',[event,'registrations']))[0];await rpc('save_bulk_cell',[event,'registrations',r.id,r.version,{mobile:'0123456789'},null]);await assert.rejects(rpc('save_bulk_cell',[event,'registrations',r.id,r.version,{mobile:'lost edit'},null]),/Record changed/);r=(await rpc('get_bulk_workspace',[event,'registrations']))[0];await assert.rejects(rpc('save_bulk_cell',[event,'registrations',r.id,r.version,{event_id:admin},null]),/not editable/);assert.equal((await db.query('select count(*)::int n from workspace_audit')).rows[0].n,1);});
await t.test('charge edits recalculate VAT and require reason',async()=>{let r=(await rpc('get_bulk_workspace',[event,'charges']))[0];await assert.rejects(rpc('save_bulk_cell',[event,'charges',r.id,r.version,{quantity:2},'']),/reason/);await rpc('save_bulk_cell',[event,'charges',r.id,r.version,{quantity:2},'Additional lesson']);r=(await rpc('get_bulk_workspace',[event,'charges'])).find(x=>x.id===r.id);assert.equal(Number(r.gross_amount),240);});
await t.test('partial batch errors remain attributable to each attendee',async()=>{const result=await rpc('bulk_billing_action',[event,'generate',ids]);assert.equal(result.length,20);assert.ok(result.every(r=>!r.ok&&r.error));for(const id of ids)await rpc('save_finance_transfer_package',[id,null,true,'Training waiver']);const checked=await rpc('bulk_billing_action',[event,'check',ids]);assert.ok(checked.every(r=>r.ok),JSON.stringify(checked));});
await t.test('batch generates twenty invoices and reuses them on repeat',async()=>{let result=await rpc('bulk_billing_action',[event,'generate',ids]);assert.ok(result.every(r=>r.ok),JSON.stringify(result));invoices=result.flatMap(r=>r.invoice_ids);assert.equal(new Set(invoices).size,20);const repeat=await rpc('bulk_billing_action',[event,'generate',ids]);assert.deepEqual(repeat.flatMap(r=>r.invoice_ids).sort(),invoices.sort());});
await t.test('twenty unique payment links, complete export and confirmation',async()=>{for(const row of await rpc('get_bulk_workspace',[event,'invoices']))await rpc('save_bulk_cell',[event,'invoices',row.id,row.version,{payment_link:`https://pay.example.invalid/${row.id}`},null]);const exported=await rpc('export_bulk_workspace',[event,'invoices','xlsx',invoices,['invoice_reference','gross_total'],{}]);assert.equal(exported.rows.length,20);assert.ok(exported.audit_id);const result=await rpc('bulk_billing_action',[event,'confirm',invoices]);assert.ok(result.every(r=>r.ok),JSON.stringify(result));});
await t.test('test dispatch persists twenty jobs and repeated queue does not duplicate',async()=>{await assert.rejects(rpc('queue_invoice_dispatch',[event,invoices,false]),/disabled/);const results=await rpc('queue_invoice_dispatch',[event,invoices,true]);assert.ok(results.every(r=>r.ok),JSON.stringify(results));const repeat=await rpc('queue_invoice_dispatch',[event,invoices,true]);assert.deepEqual(repeat.map(r=>r.job.id),results.map(r=>r.job.id));assert.equal(new Set(results.map(r=>r.job.recipient_email)).size,20);const row=(await rpc('get_bulk_workspace',[event,'invoices']))[0];await assert.rejects(rpc('save_bulk_cell',[event,'invoices',row.id,row.version,{payment_link:'https://changed.example.invalid'},null]),/frozen/);await assert.rejects(rpc('claim_invoice_dispatch_service',[results[0].job.id,admin]),/permission denied/);await actor(admin,'service_role');const claim=await rpc('claim_invoice_dispatch_service',[results[0].job.id,admin]);assert.equal(claim.claimed,true);assert.equal((await rpc('claim_invoice_dispatch_service',[results[0].job.id,admin])).claimed,false);await actor(admin);});
await t.test('Finance, Protocol and anonymous cannot access isolated test data',async()=>{for(const id of [finance,protocol]){await actor(id);await assert.rejects(rpc('get_bulk_workspace',[event,'registrations']),/Admin only/);await assert.rejects(rpc('bulk_billing_action',[event,'generate',ids]),/Admin only/);}await actor(admin,'anon');await assert.rejects(rpc('get_bulk_workspace',[event,'invoices']),/permission denied/);await actor(admin);await assert.rejects(db.exec('delete from workspace_audit'),/permission denied/);await assert.rejects(db.exec('update invoice_dispatch_jobs set status=\'accepted\''),/permission denied/);});
}finally{await db.close();}});
test('spreadsheet input conversion and complete submitted fields',()=>{assert.equal(typedValue('false',true,'equipment_hire_required'),false);assert.throws(()=>typedValue('maybe',true,'equipment_hire_required'));assert.throws(()=>typedValue('abc',1,'quantity'));assert.deepEqual(typedValue('["2028-02-01"]',[],'lesson_dates'),['2028-02-01']);assert.deepEqual(typedValue('["2028-02-01"]',[],'submitted_lesson_dates'),['2028-02-01']);assert.equal(flattenRegistration({requested:{unusual_answer:'Example'}}).submitted_unusual_answer,'Example');assert.equal(registrationEditable({entity:'attendees',registration_id:'linked',requested:{custom_question:'yes'}},'submitted_custom_question'),true);assert.equal(registrationEditable({entity:'attendees',registration_id:'linked',requested:{email:'old@example.invalid'}},'submitted_email'),false);});
test('registration worksheet saves submitted answers at their source and exports corrected values',async()=>{
 const db=await loadDB();const rpc=async(n,args)=>(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 try{await seedBulk(db);const linked='e2000000-0000-4000-8000-000000000001',intakeOnly='e2000000-0000-4000-8000-000000000002';
 await db.exec(`insert into booking_requests(event_id,attendee_id,status,first_name,surname,email,lesson_type,source_payload) values('${event}','${linked}','accepted','Training 1','Person 1','training1@example.invalid','Group','{"lesson_type":"Group","custom_question":"Old answer"}');
 insert into intake_submissions(event_id,mapped_attendee_id,raw_payload) values('${event}','${linked}','{"lesson_type":"Group","custom_question":"Old answer"}'),('${event}','${intakeOnly}','{"custom_question":"Intake answer"}');set role authenticated;`);
 let rows=await rpc('get_bulk_workspace',[event,'registrations']);let linkedRow=rows.find(r=>r.id===linked),intakeRow=rows.find(r=>r.id===intakeOnly);
 assert.equal(flattenRegistration(linkedRow).submitted_lesson_type,'Group');
 await rpc('save_bulk_cell',[event,'registrations',linked,linkedRow.version,{submitted_lesson_type:'Private',submitted_custom_question:'Corrected answer'},'Registration correction']);
 await rpc('save_bulk_cell',[event,'registrations',intakeOnly,intakeRow.version,{submitted_custom_question:'Corrected intake'},'Registration correction']);
 rows=await rpc('get_bulk_workspace',[event,'registrations']);linkedRow=rows.find(r=>r.id===linked);intakeRow=rows.find(r=>r.id===intakeOnly);
 assert.equal(flattenRegistration(linkedRow).submitted_lesson_type,'Private');assert.equal(flattenRegistration(linkedRow).submitted_custom_question,'Corrected answer');assert.equal(flattenRegistration(intakeRow).submitted_custom_question,'Corrected intake');
 assert.equal((await db.query('select lesson_type from booking_requests where attendee_id=$1',[linked])).rows[0].lesson_type,'Private');
 assert.equal((await db.query('select raw_payload->>\'lesson_type\' answer from intake_submissions where mapped_attendee_id=$1',[linked])).rows[0].answer,'Private');
 assert.equal((await db.query('select raw_payload->>\'custom_question\' answer from intake_submissions where mapped_attendee_id=$1',[intakeOnly])).rows[0].answer,'Corrected intake');
 const exported=await rpc('export_bulk_workspace',[event,'registrations','csv',[linked,intakeOnly],['submitted_lesson_type','submitted_custom_question'],{}]);
 assert.equal(exported.rows.find(r=>r.id===linked).submitted_lesson_type,'Private');assert.equal(exported.rows.find(r=>r.id===intakeOnly).submitted_custom_question,'Corrected intake');
 const bytes=await workbookBuffer(ExcelJS,[{name:'Registrations',rows:exported.rows,columns:['submitted_lesson_type','submitted_custom_question']}]);const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);assert.equal(book.worksheets[0].getCell('A2').value,'Private');
 assert.ok((await db.query("select count(*)::int n from workspace_audit where entity in ('booking_requests','intake_submissions')")).rows[0].n>=2);
 }finally{await db.close();}
});
test('batch company billing includes full charges and operational edits retain approvals',async()=>{
 const db=await loadDB();const rpc=async(n,args)=>(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 try{await seedBulk(db);await db.exec('set role authenticated');let people=(await rpc('get_bulk_workspace',[event,'registrations'])).slice(0,2);const org=await rpc('create_finance_billing_company',[event,{name:'TRAINING Thales example',email:'company@example.invalid'}]);
 await db.exec(`reset role;insert into rate_card(event_id,rate_code,description,charge_category,unit,unit_price,vat_rate,status) values('${event}','2028_TRANSFER_GVA','Airport transfer','transfer','package',200,0,'approved');insert into travel_records(attendee_id,direction,transfer_requested,transfer_chargeable,protocol_confirmed) values('${people[0].id}','arrival',true,false,true);insert into lift_passes(attendee_id,required,chargeable,protocol_confirmed) values('${people[0].id}',false,false,true);set role authenticated;`);
 await assert.rejects(rpc('save_finance_transfer_package',[people[0].id,'2028_TRANSFER_GVA',false,null]),/chargeable transfer/i);
 let review=(await rpc('get_bulk_workspace',[event,'transfer_review']))[0];await assert.rejects(rpc('save_bulk_cell',[event,'transfer_review',review.id,review.version,{transfer_chargeable:true},null]),/reason/);await rpc('save_bulk_cell',[event,'transfer_review',review.id,review.version,{transfer_chargeable:true,billing_reviewed:true,billing_review_notes:'Training airport journey reviewed'},'Agreed airport transfer charge']);await rpc('save_finance_transfer_package',[people[0].id,'2028_TRANSFER_GVA',false,null]);await rpc('save_finance_transfer_package',[people[1].id,null,true,'Training waiver']);
 const lift=(await rpc('get_bulk_workspace',[event,'lift_passes']))[0];await assert.rejects(rpc('save_bulk_cell',[event,'lift_passes',lift.id,lift.version,{notes:'Correction'},null]),/justification/);await rpc('save_bulk_cell',[event,'lift_passes',lift.id,lift.version,{notes:'Correction'},'Training correction']);assert.equal((await db.query('select notes from lift_passes where id=$1',[lift.id])).rows[0].notes,null);assert.equal((await db.query('select count(*)::int n from lift_change_requests')).rows[0].n,1);
 for(const p of people){await rpc('mark_finance_attendee_checked',[p.id,false,null]);const data=await rpc('get_attendee_billing_plan',[p.id]);await rpc('save_attendee_billing_plan',[p.id,org,'combined',Object.fromEntries(data.charges.map(c=>[c.charge_key,{kind:'percent',value:100}])),data.signature,0]);}
 const result=await rpc('bulk_billing_action',[event,'generate',people.map(p=>p.id)]);assert.ok(result.every(r=>r.ok),JSON.stringify(result));const ids=[...new Set(result.flatMap(r=>r.invoice_ids))];assert.equal(ids.length,1);const inv=(await db.query('select gross_total from invoices where id=$1',ids)).rows[0];assert.equal(Number(inv.gross_total),440);const lines=(await db.query('select attendee_name_snapshot,description from invoice_lines where invoice_id=$1',ids)).rows;assert.equal(new Set(lines.map(l=>l.attendee_name_snapshot)).size,2);assert.ok(lines.some(l=>l.description.includes('Airport transfer')));
 }finally{await db.close();}
});
test('Finance amends accommodation charges in the financial table and requests lift changes',async()=>{
 const db=await loadDB();const live='e1000000-0000-4000-8000-000000000002',person='e2000000-0000-4000-8000-000000000101';
 const rpc=async(n,args)=>(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 try{await seedBulk(db);await db.exec(`insert into events(id,name,event_year,start_date,end_date,invoice_prefix,active) values('${live}','ISSSC 2029 CHARGE TRAINING',2029,'2029-01-30','2029-02-06','LOCAL-29',true);
 insert into attendees(id,event_id,first_name,surname,email,category) values('${person}','${live}','Financial','Example','finance-person@example.invalid','Sponsor');
 insert into rate_card(event_id,rate_code,description,charge_category,unit,unit_price,vat_rate,status) values
 ('${live}','HOTEL-A','Hotel A','accommodation','night',100,0,'approved'),('${live}','HOTEL-B','Hotel B','accommodation','night',125,0,'approved'),
 ('${live}','LIFT-A','Lift A','lift_pass','day',50,0,'approved'),('${live}','LIFT-B','Lift B','lift_pass','day',60,0,'approved');
 insert into stay_charge_periods(attendee_id,billing_from,billing_to,rate_code,protocol_confirmed) values('${person}','2029-01-30','2029-02-06','HOTEL-A',true);
 insert into lift_passes(attendee_id,required,start_date,end_date,carre_neige_required,chargeable,rate_code,protocol_confirmed) values('${person}',true,'2029-01-30','2029-02-01',true,true,'LIFT-A',true);
 select set_config('request.jwt.claim.sub','${finance}',false);set role authenticated;`);
 let charges=await rpc('get_bulk_workspace',[live,'charges']);const stay=charges.find(r=>r.entity==='stay'),lift=charges.find(r=>r.entity==='lift_pass');assert.ok(stay&&lift,JSON.stringify(charges));
 await assert.rejects(rpc('save_bulk_cell',[live,'charges',stay.id,stay.version,{rate_code:'HOTEL-B'},null]),/reason/);
 await rpc('save_bulk_cell',[live,'charges',stay.id,stay.version,{rate_code:'HOTEL-B'},'Corrected agreed room rate']);
 charges=await rpc('get_bulk_workspace',[live,'charges']);assert.equal(Number(charges.find(r=>r.entity==='stay').net_amount),875);
 const currentLift=charges.find(r=>r.entity==='lift_pass');await rpc('save_bulk_cell',[live,'charges',currentLift.id,currentLift.version,{rate_code:'LIFT-B'},'Corrected lift tariff']);
 assert.equal((await db.query('select rate_code from lift_passes where attendee_id=$1',[person])).rows[0].rate_code,'LIFT-A');
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','${admin}',false);set role authenticated;`);
 const pending=(await db.query('select id from lift_change_requests where attendee_id=$1',[person])).rows;assert.equal(pending.length,1);
 await rpc('review_lift_change',[pending[0].id,true,'Approved corrected tariff']);
 assert.equal((await db.query('select rate_code from lift_passes where attendee_id=$1',[person])).rows[0].rate_code,'LIFT-B');
 }finally{await db.close();}
});
